@startuml
title カレーライス
start
:具材を買う;
:米を洗う;
fork
:ジャガイモとニンジンを洗う;
:ジャガイモとニンジンと玉ねぎの皮をむく;
:ジャガイモとニンジンと玉ねぎを炒める;
:水を入れて沸騰させる;
:カレールを入れる;
:煮込む;
fork again
:米を炊く;
end fork
:ごはんにカレールを盛り付ける;
:食べる;
stop
@enduml