@startuml 診察予約
[*] -right-> メニュー : 接続
メニュー -right-> [*]
メニュー ---> 予約と確認 : 予約
予約と確認 -right--> あなたの順番 : 確認
あなたの順番 -up--> メニュー : 取り消し
予約と確認 -right--> あなたの順番 : 登録
メニュー ---> 今の順番 : 患者の順番表示
今の順番 ---> メニュー : 看護師が患者番号を一つ増やす
予約と確認 --> メニュー : 戻る
@enduml
