@startuml
|販売代理店|
start
:発注;
|A社|
:営業部門;
:在庫調査;
if() then (在庫なし)
|A社|
:;
    note right
    作図の都合上、
    ダミーの
    アクティビティ図
    を記述
    end note
else(在庫あり)
|原材料メーカー|
:製造;
endif
|A社|
:発送;
|販売代理店|
:検収/支払い;
|A社|
:入金確認;
stop
@enduml